services:

  adminer:
    ports:
      - ${ADMINER_PUBLISH_PORT}:8080

  cassandra:
    ports:
      - ${CASSANDRA_PUBLISH_PORT}:9042

  cassandra-node1:
    ports:
      - ${CASSANDRA_NODE1_PUBLISH_PORT}:9042
    volumes:
      - common-cassandra-dse-db:/var/lib/cassandra/data

  cassandra-node2:
    ports:
      - ${CASSANDRA_NODE2_PUBLISH_PORT}:9042
    volumes:
      - common-cassandra-dse-db:/var/lib/cassandra/data

  cassandra-node3:
    ports:
      - ${CASSANDRA_NODE3_PUBLISH_PORT}:9042
    volumes:
      - common-cassandra-dse-db:/var/lib/cassandra/data

  elasticsearch:
    ports:
      - ${ELASTICSEARCH_PUBLISH_PORT}:9200

  fluentd:
    ports:
      - ${FLUENTD_PUBLISH_PORT}:24224
      - ${FLUENTD_PUBLISH_PORT}:24224/udp

  grafana:
    ports:
      - ${GRAFANA_PUBLISH_PORT}:3000

  jaeger:
    ports:
      - 127.0.0.1:${JAEGER_PUBLISH_PORT}:16686

  kibana:
    ports:
      - ${KIBANA_PUBLISH_PORT}:5601

  ldapadmin:
    ports:
      - ${LDAPADMIN_PUBLISH_PORT}:80

  maildev:
    ports:
      - ${MAILDEV_PUBLISH_PORT}:1080

  mailhog:
    ports:
      - ${MAILHOG_PUBLISH_PORT}:8025

  minio:
    ports:
      - ${MINIO_API_PUBLISH_PORT}:9000
      - ${MINIO_CONSOLE_PUBLISH_PORT:-9001}:${MINIO_CONSOLE_PUBLISH_PORT:-9001}
    volumes:
      - ./minio/certs:/root/.minio/certs

  minio-client:
    volumes:
      - ./minio/policies:/minio-policies

  minio-nginx:
    ports:
      - ${MINIO_NGINX_API_PUBLISH_PORT}:443
      - ${MINIO_NGINX_CONSOLE_PUBLISH_PORT}:444

  mysql:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=1
    ports:
      - ${MYSQL_PUBLISH_PORT}:3306

  nfs-server:
    ports:
      - ${NFS_SERVER_PUBLISH_PORT}:2049

  oracle:
    shm_size: 1g
    ports:
      - ${ORACLE_PUBLISH_PORT}:1521

  portainer:
    ports:
      - ${PORTAINER_PUBLISH_PORT}:9443

  redis:
    ports:
      - ${REDIS_PUBLISH_PORT}:6379

  redis-slave:
    ports:
      - ${REDIS_SLAVE_PUBLISH_PORT}:6379

  redis-sentinel:
    ports:
      - ${REDIS_SENTINEL_PUBLISH_PORT}:26379

  redis-commander:
    ports:
      - ${REDIS_COMMANDER_PUBLISH_PORT}:8081

  redisearch:
    # image: docker.io/your-id/redisearch:${REDISEARCH_IMAGE_TAG}-0
    ports:
      - ${REDISEARCH_PUBLISH_PORT}:6379

  redisearch-slave:
    # image: docker.io/your-id/redisearch:${REDISEARCH_IMAGE_TAG}-0
    ports:
      - ${REDISEARCH_SLAVE_PUBLISH_PORT}:6379

  rabbitmq:
    ports:
      - ${RABBITMQ_PUBLISH_PORT}:15672

  traefik:
    labels:
      - "traefik.http.routers.traefik=true"
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  postgres:
    ports:
      - ${POSTGRES_PUBLISH_PORT}:5432
    volumes:
      - common-postgres-data:/var/lib/postgresql/data

  zookeeper:
    ports:
      - ${ZOOKEEPER_PUBLISH_PORT}:2181

  coordinator:
    volumes:
      - common-druid-shared:/opt/shared
      - common-coordinator-var:/opt/druid/var
    ports:
      - ${APACHE_DRUID_COORDINATOR_PUBLISH_PORT}:8081

  broker:
    volumes:
      - common-broker-var:/opt/druid/var
    ports:
      - ${APACHE_DRUID_BROKER_PUBLISH_PORT}:8082

  historical:
    volumes:
      - common-druid-shared:/opt/shared
      - common-historical-var:/opt/druid/var
    ports:
      - ${APACHE_DRUID_HISTORICAL_PUBLISH_PORT}:8083

  middlemanager:
    volumes:
      - common-druid-shared:/opt/shared
      - common-middlemanager-var:/opt/druid/var
    ports:
      - ${APACHE_DRUID_MIDDLEMANAGER_PUBLISH_PORT}:8091
      - ${APACHE_DRUID_MIDDLEMANAGER_PUBLISH_PORT_RANGE}:8100-8105

  router:
    volumes:
      - common-router-var:/opt/druid/var
    ports:
      - ${APACHE_DRUID_ROUTER_PUBLISH_PORT}:8888
