volumes:
  common-jaeger:
    name: 'common-jaeger'

services:

  jaeger:
    image: 'jaegertracing/all-in-one:${JAEGER_IMAGE_TAG}'
    env_file:
      - .envs/jaeger.env
    networks:
      common-net:
        aliases:
          - common-jaeger
    volumes:
      - common-jaeger:/tmp
