# Official doc: https://www.dragonflydb.io/docs/getting-started/docker-compose
volumes:
  common-dragonfly-db:
    name: 'common-dragonfly-db'

services:

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    env_file:
      - .envs/dragonfly.env
    ulimits:
      memlock: -1
    volumes:
      - common-dragonfly-db:/data
    networks:
      common-net:
        aliases:
          - common-dragonfly
