volumes:

  common-postgres-data:
    name: 'common-postgres-data'

services:

  postgres:
    container_name: common-postgres
    image: postgres:${POSTGRES_IMAGE_TAG}
    env_file:
      - .envs/postgres.env
    networks:
      common-net:
        aliases:
          - common-postgres