volumes:
  common-jaeger:
    name: 'common-jaeger'

services:
  jaeger:
    image: 'jaegertracing/jaeger:${JAEGER_IMAGE_TAG:-2.1.0}'
    env_file:
      - .env
    networks:
      common-net:
        aliases:
          - common-jaeger
    volumes:
      - common-jaeger:/tmp
