volumes:
  common-jaeger:
    name: 'common-jaeger'

services:
  jaeger:
    image: 'jaegertracing/jaeger:${JAEGER_IMAGE_TAG:-2.2.0}'
    env_file:
      - .env
    networks:
      common-net:
        aliases:
          - common-jaeger
    ports:
      - 127.0.0.1:${JAEGER_PUBLISH_PORT:-16686}:16686
    volumes:
      - common-jaeger:/tmp
    deploy:
      resources:
        limits:
          memory: '8G'
