volumes:
  elasticsearch-data:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_KIBANA_IMAGE_TAG:-8.15.2}
    env_file:
      - .env
    networks:
      common-net:
        aliases:
          - common-elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data/
      - ./certs:/usr/share/elasticsearch/config/certs
    deploy:
      resources:
        limits:
          memory: 1GB
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
