services:
  adminer:
    image: 'ghcr.io/shyim/adminerevo:${ADMINER_IMAGE_TAG:-4.8.4}'
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 256MB
    networks:
      - common-net
    ports:
      - 127.0.0.1:${ADMINER_PUBLISH_PORT:-8000}:8080
