volumes:
  common-mysql:
    name: 'common-mysql'

services:
  mysql:
    image: 'bitnami/mysql:${MYSQL_IMAGE_TAG:-8.4.3}'
    env_file:
      - .env
    networks:
      common-net:
        aliases:
          - common-mysql
    # ports:
    #   - 127.0.0.1:${MYSQL_PUBLISH_PORT:-3306}:3306
    volumes:
      - common-mysql:/var/lib/mysql
      - ./my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
      - ./sqls:/sqls
      - ./csvs:/csvs
